ALTER TABLE "core"."organization"
  ADD COLUMN IF NOT EXISTS "mission" TEXT NULL,
  ADD COLUMN IF NOT EXISTS "vision" TEXT NULL,
  ADD COLUMN IF NOT EXISTS "values" TEXT NULL,
  ADD COLUMN IF NOT EXISTS "context" TEXT NULL;
