name: gestion-publica-db

services:
  postgres:
    image: postgres:16-alpine
    container_name: gestion_publica_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: gp_user
      POSTGRES_PASSWORD: gp_password
      POSTGRES_DB: gestion_publica
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gp_user -d gestion_publica"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
